version: 2.1
notify-sentry-deploy:
  executor:
  # Specify executor for running deploy job
  environment:
    SENTRY_ORG: orange-county
    SENTRY_PROJECT: oc-orange-county-lettings
    SENTRY_ENVIRONMENT: production
  steps:
    - checkout
    - run:
        name: Create release and notify Sentry of deploy
        command: |
          curl -sL https://sentry.io/get-cli/ | bash
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits $SENTRY_RELEASE --auto
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps path-to-sourcemaps-if-applicable
          sentry-cli releases finalize $SENTRY_RELEASE
          sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT

jobs:
  test: 
    docker:
      - image: "cimg/python:3.9.2"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            python3 -m pip install -r requirements.txt
            python3 manage.py test
  linting: 
    docker:
      - image: "cimg/python:3.9.2"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run linter
          command: |
            python3 -m pip install -r requirements.txt
            python3 -m flake8
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t orange-county-app .
      - run:
          name: Push Image
          command: |
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
            docker tag orange-county-app "sebdevdock/orange_county_lettings:${CIRCLE_SHA1}"
            docker push "sebdevdock/orange_county_lettings:${CIRCLE_SHA1}"

workflows:
  build-and-test: 
    jobs:
      - linting
      - test:
          requires:
            - linting
      - build:
          requires:
            - test
      - notify-sentry-deploy:
          requires:
            - build
