version: 2.1

orbs:
  
  python: circleci/python@1.5.0
  docker: circleci/docker@2.1.2


jobs:
  build:
    docker:
      - image: alpine:3.16

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t orange-county-app .
      - run:
          name: Push Image
          command: |
            docker tag orange-county-app "${ECR_ENDPOINT}/orange-county-app:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}/orange-county-app:${CIRCLE_SHA1}"
  test: 
    docker:
      - image: "${ECR_ENDPOINT}/orange-county-app:${CIRCLE_SHA1}"
    
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 manage.py test
  linting: 
    docker:
      - image: "${ECR_ENDPOINT}/orange-county-app:${CIRCLE_SHA1}"
    
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linter
          command: flake8


workflows:
  build-and-test: 
    jobs:
      - build
      - test
      - linting
