version: 2.1

orbs:
  
  python: circleci/python@1.5.0


jobs:
  
  test: 
    docker:
      - image: cimg/python:3.10.2
    
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 manage.py test
  linting: 
    docker:
      - image: cimg/python:3.10.2
    
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linter
          command: python3 flake8


workflows:
  build-and-test: 
    jobs:
      - test
      - linting
