version: 2.1

orbs:
  
  python: circleci/python@1.5.0


jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 manage.py test


workflows:
  sample: 
    jobs:
      - build-and-test
