version: 2.1

orbs:
  
  python: circleci/python@1.5.0
  docker: circleci/docker@2.1.2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t orange-county-app .
      - run:
          name: Push Image
          command: |
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
            docker tag orange-county-app "sebdevdock/orange_county_lettings:${CIRCLE_SHA1}"
            docker push "sebdevdock/orange_county_lettings:${CIRCLE_SHA1}"
  test: 
    docker:
      - image: "sebdevdock/orange_county_lettings:${CIRCLE_SHA1}"
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 manage.py test
  linting: 
    docker:
      - image: "sebdevdock/orange_county_lettings:${CIRCLE_SHA1}"
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linter
          command: flake8


workflows:
  build-and-test: 
    jobs:
      - build
      - test:
          requires:
            - build
      - linting:
          requires:
            - test
