# Generated by Django 3.2.13 on 2022-06-15 19:30

from django.db import migrations

def feed_table(table, data):
    native_data = [dict(record) for record in data]
    for record in native_data:
        table.objects.create(**record)
    return table

def migrate_data(apps, schema_migration):

    old_address_model = apps.get_model('oc_lettings_site', 'address')
    new_address_model = apps.get_model('lettings', 'address')

    old_lettings_model = apps.get_model('oc_lettings_site', 'letting')
    new_lettings_model = apps.get_model('lettings', 'letting')

    # Migrate new model address
    feed_table(new_address_model, old_address_model.objects.values())

    # Migrate new model lettings
    feed_table(new_lettings_model, old_lettings_model.objects.values())


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220613_0841'),
        ('lettings', '0001_initial'),

    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
