# Generated by Django 3.2.13 on 2022-06-18 08:29

from django.db import migrations


def feed_table(table, data):
    native_data = [dict(record) for record in data]
    for record in native_data:
        table.objects.create(**record)
    return table

def migrate_data(apps, schema_migration):

    old_profiles_model = apps.get_model('oc_lettings_site', 'profile')
    new_profiles_model = apps.get_model('profiles', 'profile')

    # Migrate new model address
    feed_table(new_profiles_model, old_profiles_model.objects.values())



class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20220613_0905'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
