# Generated by Django 3.2.13 on 2022-06-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0005_auto_20220618_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
